language: python
dist: trusty
sudo: false
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -r requirements.dev.txt
script:
- PYTHONPATH=./:build/lib.linux-x86_64-3.6/:$PYTHONPATH pytest -v --cov=emtrees --cov-report html --cov-report term-missing --cov-branch
