language: python
dist: trusty
sudo: false
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest-cov
script:
- pytest -v --cov=emtrees --cov-report html --cov-report term-missing --cov-branch
